### ISSUE TITLE
Algunas imágenes del README no cargan correctamente

### ISSUE THREAD

**Issue by Asmilex** [JAntonioVR/Geometria-Fractal#64]
Parece que se debe a enlazar directamente los ficheros de otros hosts. Quizás se podría solucionar agregándolas a este repositorio. 

Foto de ejemplo: 

![image](https://user-images.githubusercontent.com/32983998/171434396-37906038-e359-4104-aa8f-216ba779b23e.png)

**Comment by JAntonioVR** [comment]
De todas formas ese README tiene las horas contadas, lo hice al empezar el proyecto, tengo que actualizarlo con imágenes propias, gracias por el apunte! @Asmilex
